version: '1'

networks:
  library:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis:

services:
  container_name: api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
    - "postgres_db"
    environment:
      - Postgre_Connection_String=User Id=postgres; Password=123;Server=postgres_db;Port=5432;Database=users; IntegratedSecurity=true;
      - Redis_Connection_String=redis_connection_string
    ports: 
      - "8088:80"
    networks:
      - postgres



  postgres_db:
  container_name: postgres
  image: postgres:13.3
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123
    - POSTGRES_DB=users
    - PGDATA=/data/postgres
  volumes:
      - postgres:/data/postgres
  ports:
    - "5433:5432"
  networks:
    - library
  

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - library
    restart: unless-stopped

  redis: 
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - library
    volumes:
      - redis:/data/redis

